# Generated by Django 4.2.25 on 2025-10-20 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='TransaccionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (+/-)')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('gasto', 'Gasto'), ('apertura_caja', 'Apertura de Caja'), ('cierre_caja', 'Cierre de Caja'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('object_id', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.metodopago', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Transacción de Caja',
                'verbose_name_plural': 'Transacciones de Caja (Ledger)',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pagado por')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
