# Generated by Django 4.2.25 on 2025-10-20 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255, verbose_name='Acción')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='ID Objeto')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Objeto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad (Auditoría)',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seguridad_r_content_1a4542_idx')],
            },
        ),
    ]
