# Generated by Django 4.2.25 on 2025-10-20 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_listaprecios_alter_conversionunidad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('documento_identidad', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Documento (RUC/DNI)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('lista_precios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.listaprecios', verbose_name='Lista de Precios')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (si aplica)')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('parcialmente_recibido', 'Parcialmente Recibido'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='borrador', max_length=30, verbose_name='Estado')),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Esperada')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Total')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Documento Proveedor')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('condiciones_pago', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='SesionPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_apertura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Apertura')),
                ('saldo_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Cierre')),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10, verbose_name='Estado')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion', verbose_name='Ubicación (Caja)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Cajero)')),
            ],
            options={
                'verbose_name': 'Sesión POS',
                'verbose_name_plural': 'Sesiones POS',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('pos', 'POS (Tienda)'), ('web', 'Web (E-commerce)')], default='pos', max_length=10, verbose_name='Canal')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pedido_recibido', 'Pedido Recibido (Web)'), ('pendiente_pago', 'Pendiente de Pago'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_pago', models.CharField(default='pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Documento (Boleta/Factura)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.cliente', verbose_name='Cliente')),
                ('sesion_pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.sesionpos', verbose_name='Sesión POS')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_en_venta', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Costo (COGS)')),
                ('numero_lote_usado', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Lote Usado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto', verbose_name='Producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.unidad', verbose_name='Unidad')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.varianteproducto', verbose_name='Variante')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Ítem de Venta',
                'verbose_name_plural': 'Ítems de Venta',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Costo Unitario')),
                ('numero_lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Lote')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.ordencompra', verbose_name='Orden de Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto', verbose_name='Producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.unidad', verbose_name='Unidad')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.varianteproducto', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Ítem de Orden de Compra',
                'verbose_name_plural': 'Ítems de Órdenes de Compra',
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.unidad')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.varianteproducto')),
            ],
            options={
                'verbose_name': 'Ítem de Carrito',
                'verbose_name_plural': 'Ítems de Carrito',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente'),
        ),
    ]
